version: '3.4'

services:
  authapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  vote_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

