version: '3.4'

services:
  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    depends_on:
        - mariadb
    build:
      context: .
      dockerfile: Auth_API/Dockerfile
    ports:
        - "5001:80"
    environment:
        JWTSECRET: 
        ARGON2SECRET: 
        SERVER: mariadb
        DATABASE: auth
        PORT: 3306
        USERNAME: root
        PASSWORD: qwerty
        SPOTIFYCLIENTID:
        SPOTIFYCLIENTSECRET:
        SMTPHOST: smtp.gmail.com
        SMTPPORT: 587
        EMAILADDRESS: example.com
        EMAILPASSWORD: f4f34f
        FRONTENDURL: http://localhost:3000/

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ~/apps/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  vote_api:
    image: ${DOCKER_REGISTRY-}voteapi
    depends_on:
        - mariadb
    build:
      context: .
      dockerfile: Vote_API/Dockerfile
    ports:
        - "5002:80"
    environment:
        JWTSECRET: hwef9hewihsidhfkfdafew
        SERVER: mariadb
        DATABASE: vote
        PORT: 3306
        USERNAME: root
        PASSWORD: qwerty
        SERVERURL: 127.0.0.1
        ARGON2SECRET: fho938fh32oewfjfefj2398
        FRONTENDURL: https://laser-vote.vdarwinkel.nl/